# TASK - 5: Demonstrate column transformation

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
X= df.iloc[:,:-1]
X.values

array([[0, 3, 'male', ..., nan, 'Southampton', 'no'],
       [1, 1, 'female', ..., 'C', 'Cherbourg', 'yes'],
       [1, 3, 'female', ..., nan, 'Southampton', 'yes'],
       ...,
       [0, 3, 'female', ..., nan, 'Southampton', 'no'],
       [1, 1, 'male', ..., 'C', 'Cherbourg', 'yes'],
       [0, 3, 'male', ..., nan, 'Queenstown', 'no']], dtype=object)

In [4]:
y=df.iloc[:,-1]
y.values

array([False, False,  True, False,  True,  True,  True, False, False,
       False, False,  True,  True, False,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
       False,  True,  True,  True, False,  True,  True, False, False,
        True,  True, False, False, False, False,  True, False,  True,
        True, False,  True, False, False, False,  True, False, False,
       False,  True,  True,  True, False, False,  True,  True, False,
       False,  True, False,  True,  True, False, False,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True,  True, False, False,  True,  True,  True, False, False,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
       False, False, False, False,  True, False,  True, False, False,
        True,  True,

In [5]:
X.iloc[:,1:3]

pclass     sex
0         3    male
1         1  female
2         3  female
3         1  female
4         3    male
..      ...     ...
886       2    male
887       1  female
888       3  female
889       1    male
890       3    male

[891 rows x 2 columns]

In [6]:
X

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  
0      man        True  NaN  Southampton    no  
1    woman       False    C    Cherbourg   yes  
2    woman       False  NaN  Southampton   yes  
3    woman       False    C  Southampton   yes  
4      man        True  NaN  Southampton    no  
..     ...         ...  ...          ...   ...  
886    man        True  NaN  Southampton    no  
887  woman       False    B  Southampton   yes  
888  woman       False  NaN  Southampton    no  
889    man        True    C    Cherbourg   yes  
890    man        True  NaN   Queenstown    no  

[891 rows x 14 columns]

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer

In [8]:
ohe= OneHotEncoder()
imp= SimpleImputer()

In [11]:
ct= make_column_transformer(
    (ohe,['embark_town']),
    (imp,['age','pclass']),
    remainder='passthrough'
)

In [12]:
X=ct.fit_transform(X)

In [13]:
X

array([[0.0, 0.0, 1.0, ..., True, nan, 'no'],
       [1.0, 0.0, 0.0, ..., False, 'C', 'yes'],
       [0.0, 0.0, 1.0, ..., False, nan, 'yes'],
       ...,
       [0.0, 0.0, 1.0, ..., False, nan, 'no'],
       [1.0, 0.0, 0.0, ..., True, 'C', 'yes'],
       [0.0, 1.0, 0.0, ..., True, nan, 'no']], dtype=object)