# TASK - 1:   Demonstrate  Working   with   numpy

## Numpy


NumPy
NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks. Numpy is also incredibly fast, as it has bindings to C libraries

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
a = [1,9,0,6,9,1,8]

In [3]:
a

[1, 9, 0, 6, 9, 1, 8]

In [4]:
ar1 = np.array(a)

In [5]:
ar1

array([1, 9, 0, 6, 9, 1, 8])

In [6]:
type(ar1)

numpy.ndarray

## max(), min(), argmax(), argmin()

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [7]:
ar1.min()

0

In [8]:
ar1.max()

9

In [9]:
ar1.argmax()

1

In [10]:
ar1.argmin()

2

In [11]:
li = [[2,5,0],[4,9,6]]

In [12]:
li

[[2, 5, 0], [4, 9, 6]]

In [13]:
m = np.array(li)

In [14]:
m

array([[2, 5, 0],
       [4, 9, 6]])

## append

The append() method in python adds a single item to the existing list

In [15]:
li.append(7)

In [16]:
li

[[2, 5, 0], [4, 9, 6], 7]

In [17]:
n = np.array(a, dtype = 'double')

In [18]:
n

array([1., 9., 0., 6., 9., 1., 8.])

## ndim()

ndim() method | Python. numpy. ndarray. ndim() function return the number of dimensions of an array

In [19]:
n.ndim

1

In [20]:
m.ndim

2

# Built-in Methods

There are lots of built-in ways to generate Arrays

## arange

Return evenly spaced values within a given interval.

In [21]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## zeros and ones

In [23]:
d = np.zeros(7)

In [24]:
d

array([0., 0., 0., 0., 0., 0., 0.])

In [25]:
d.dtype

dtype('float64')

In [26]:
d = np.zeros([4,6])

In [27]:
d

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## linspace

Return evenly spaced numbers over a specified interval.

np.linspace(0,100,)

## dtype

You can also grab the data type of the object in the array:

d.dtype

In [28]:
c = d.astype('int')

In [29]:
c

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [30]:
c.dtype

dtype('int32')

## eye

Creates an identity matrix

In [31]:
f = np.eye(7)

In [32]:
f

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [33]:
f1 = np.eye(4,3)

In [34]:
f1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## flatten

flatten() function we can flatten a matrix to one dimension in python

In [35]:
f.flatten()

array([1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.])

In [36]:
f1.flatten()

array([1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.])

## diag

The diag() function is used to extract a diagonal or construct a diagonal array

In [37]:
np.diag(f)

array([1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.diag(f1)

array([1., 1., 1.])

# Random

Numpy also has lots of ways to create random number arrays:

## rand

Create an array of the given shape and populate it with random samples from a uniform distribution over (0, 1).

In [39]:
p = np.random.rand(7,8)

In [40]:
p

array([[0.50852006, 0.56891581, 0.78453547, 0.07937547, 0.18855311,
        0.71275645, 0.21858562, 0.1949841 ],
       [0.7045612 , 0.45618271, 0.05518105, 0.92168808, 0.4774719 ,
        0.99250647, 0.35859541, 0.77987539],
       [0.58339186, 0.80563014, 0.94086126, 0.92151338, 0.78006885,
        0.82617818, 0.08735772, 0.29531919],
       [0.16066763, 0.21596118, 0.96891183, 0.98409917, 0.62721169,
        0.56141752, 0.4309832 , 0.66884949],
       [0.54643878, 0.1069686 , 0.25380133, 0.25710541, 0.13858088,
        0.39339194, 0.04162036, 0.43085433],
       [0.48108823, 0.37419295, 0.0465905 , 0.65605541, 0.3484681 ,
        0.92929031, 0.74911617, 0.15743484],
       [0.29589722, 0.47809154, 0.4386101 , 0.64633861, 0.03018502,
        0.0665677 , 0.73958333, 0.17360845]])

## randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [41]:
np.random.randn(2)

array([-0.01052369,  1.16865297])

In [42]:
np.random.randn(5,5)

array([[-0.59275099,  1.22353976,  0.15154217, -0.22696461,  0.81106736],
       [-1.24645736, -0.27156162, -0.73612177,  0.26135348,  0.69173302],
       [ 0.81956261, -1.09328206, -0.63018834,  1.73934416,  0.14068312],
       [ 0.25877154,  1.35522227,  2.41595727,  0.11445934,  0.09917489],
       [ 1.85832095,  1.99235043, -1.56787653, -1.42541978, -2.58340959]])

## randint

Return random integers from low (inclusive) to high (exclusive).

In [43]:
p1= np.random.randint(1,10,size=(3,3),dtype='int')

In [44]:
p1

array([[7, 1, 5],
       [2, 3, 1],
       [9, 7, 3]])

# Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [45]:
p2 = np.arange(20)

In [46]:
p2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Reshape

In [47]:
p2.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [48]:
p3 = p2.reshape(2,10)

In [49]:
p3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# Shape

Shape is an attribute that arrays have (not a method):

In [50]:
p3.shape

(2, 10)

In [51]:
p4 =np.random.randint(1,100,50)

In [52]:
p4

array([77, 90, 30, 95, 77, 75, 47, 83, 33, 94, 81, 94,  2, 45, 21, 69,  2,
       65, 50,  6, 19, 85, 18, 87, 59, 53, 14,  5, 97, 30, 10, 83, 24, 46,
       52, 67, 53, 85, 73, 30, 71, 87, 75, 78, 85, 63, 34, 62, 12, 27])

# Indexing a 2D array (matrices)

The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [53]:
e = np.random.randint(1,10,size=(3,3),dtype='int')

In [54]:
e

array([[9, 3, 3],
       [3, 6, 6],
       [1, 7, 3]])

In [55]:
e[0][0]

9

In [56]:
e[2][2]

3

In [57]:
e[2]

array([1, 7, 3])

# Bracket Indexing and Selection

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [58]:
e[:1]

array([[9, 3, 3]])

In [59]:
e[2:0:1]

array([], shape=(0, 3), dtype=int32)

In [60]:
e[0:2:2]

array([[9, 3, 3]])

In [61]:
e[::-1]

array([[1, 7, 3],
       [3, 6, 6],
       [9, 3, 3]])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [62]:
arr = np.arange(0,11)

In [63]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

# Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [66]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [68]:
bool_arr = arr>4

In [69]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [70]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [73]:
import numpy as np
arr = np.arange(1,11)

In [74]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [76]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
5/arr

array([5.        , 2.5       , 1.66666667, 1.25      , 1.        ,
       0.83333333, 0.71428571, 0.625     , 0.55555556, 0.5       ])

In [78]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

# Universal Array Functions

In [79]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [80]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [81]:
np.max(arr)

10

In [82]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [83]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])